name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: technote-space/assign-author@v1.3.1
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm i

    - name: Release
      run: git config --global user.email "dcucko@github.com" && git config --global user.name "cucko" && make release
