name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm i

    - name: Release
      run: make release level=patch | minor | major | 1.3.0
